jest.dontMock('../Actions')
jest.dontMock('../Dispatcher')
jest.dontMock('../utils')

var Actions = require('../Actions')

class MyTestActions extends Actions {
  constructor() {
    super()
    this.generateActions(
      'autogenerated'
    )
  }

  customAction(value) {
    this.dispatch('customName', value)
  }

  customPrefix(value) {
    this.dispatch('customPrefix', value, 'CustomPrefix')
  }
}

describe('Actions', () => {
  var MyActions

  beforeEach(() => {
    MyActions = new MyTestActions()
  })

  it('responds to generateActions()', function() {
    expect(MyActions.generateActions).not.toBeUndefined()
    expect(typeof MyActions.generateActions).toBe('function')
  })

  it('autogenerates actions', function() {
    expect(MyActions.autogenerated).not.toBeUndefined()
    expect(typeof MyActions.autogenerated).toBe('function')
  })

  it('responds to dispatch()', function() {
    expect(MyActions.dispatch).not.toBeUndefined()
    expect(typeof MyActions.dispatch).toBe('function')
  })
})
